name: App CI

on:
  push:
    # Run on all brancheses
    branches:
      - '*'
    # Run only if files modified are not docs
  pull_request:
    # Run on all branches
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  # Deploy to gh pages
  deploy:
    name: Deploy
    # Deploy only for main branch
    if: github.ref == 'refs/heads/main'
    needs: buildAndTest
    runs-on: ubuntu-latest
    # Manual deployment
    # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Download dist artifacts
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      # Deploy dist folder to gh pages
      - name: DEPLOY
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: ${{ secrets.GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}
